[package]
name = "burn_session"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "1.4.3"
casper-types = "1.4.5"

[[bin]]
name = "burn"
path = "src/main.rs"
bench = false
doctest = false
test = false